### PR TITLE
Add Read-Only handling and Silent parameter

### PR DESCRIPTION
**Pull request by davidcochrum**
- Adds `readonly` and opposing `writable` API methods and handling.
- Adds second `silent` boolean parameter to API methods.

### CODE REVIEW

**Comment by panips** [comment]
+1

**Comment by panips** [comment]
please merge this pull request. It will be a real help

**Comment by mariofischer** [comment]
+1

**Comment by bitsnaps** [comment]
Does readonly attribute works? seems it has no effect:
`<input type="checkbox" data-toggle="toggle" readonly="readonly" />`

**Pull request closed without merging**
